[package]
name = "y2021"
version.workspace = true
edition.workspace = true

[dependencies]
shared = { path = "../shared" }
regex.workspace = true
itertools.workspace = true
rayon.workspace = true
fxhash.workspace = true
nom.workspace = true
once_cell.workspace = true
anyhow.workspace = true

